# Generated by Django 5.0.6 on 2024-07-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_army_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='id_person',
            field=models.IntegerField(default=1),
        ),
    ]
