# Generated by Django 5.0.6 on 2024-07-10 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_army_id_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='castle',
            name='now_hp',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='castle',
            name='start_hp',
            field=models.IntegerField(default=100000),
        ),
    ]
