# Generated by Django 5.0.6 on 2024-07-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_picture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
