# Generated by Django 5.0.6 on 2024-07-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_person_tg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='speed',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='castle',
            name='now_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='tg_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
