# Generated by Django 5.0.6 on 2024-07-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_army_speed_alter_castle_now_hp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics_Army',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl_speed', models.IntegerField(default=1)),
                ('price_speed', models.IntegerField(default=1)),
                ('lvl_bring_money', models.IntegerField(default=1)),
                ('price_bring_money', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='now_energy',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='person',
            name='start_energy',
            field=models.IntegerField(default=500),
        ),
    ]
