# Generated by Django 5.0.6 on 2024-07-18 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_statistics_army_alter_person_now_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='statistics',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='army', to='main.statistics_army'),
        ),
    ]
