# Generated by Django 5.0.6 on 2024-07-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_army_statistics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='army',
            name='speed',
            field=models.FloatField(default=1.0),
        ),
    ]
