# Generated by Django 5.0.6 on 2024-07-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_army_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='my_army',
            field=models.ManyToManyField(blank=True, null=True, related_name='my_army', to='main.army'),
        ),
    ]
