# Generated by Django 5.0.6 on 2024-08-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_person_my_army'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='max_card',
            field=models.IntegerField(default=0),
        ),
    ]
