# Generated by Django 5.0.6 on 2024-08-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_army_max_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='army',
            old_name='max_card',
            new_name='max_cards',
        ),
    ]
