# Generated by Django 5.0.6 on 2024-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_visit_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='crystal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='week_streak',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
