# Generated by Django 5.0.6 on 2024-09-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_visit_numbers_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='week_streak',
        ),
    ]
