# Generated by Django 5.0.6 on 2024-09-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_visit_week_streak'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='get_bonus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='visit',
            name='week_streak',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Daly_Bonus',
        ),
    ]
