# Generated by Django 5.0.6 on 2024-09-27 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_visit_get_bonus_visit_week_streak_delete_daly_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='can_evolve',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PassiveEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=1)),
                ('profit_in_hour', models.PositiveIntegerField(default=1)),
                ('cooldown', models.PositiveIntegerField(default=1)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passive_earning', to='main.picture')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passive_earning', to='main.person')),
            ],
        ),
    ]
