# Generated by Django 5.0.6 on 2024-10-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_person_castles_destroyed_person_friends_invited_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='army',
            name='lvl_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='army',
            name='price_capacity',
            field=models.IntegerField(default=1),
        ),
    ]
