# Generated by Django 5.0.6 on 2024-10-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_army_capacity_army_lvl_capacity_army_price_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='army',
            name='current_units',
            field=models.IntegerField(default=1, verbose_name='Текущее количество юнитов'),
        ),
        migrations.AlterField(
            model_name='army',
            name='capacity',
            field=models.IntegerField(default=1, verbose_name='Максимальное количество юнитов этого типа'),
        ),
    ]
