# Generated by Django 5.0.6 on 2024-10-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_person_last_update_time_energy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='army',
            old_name='id_person',
            new_name='id_warrior',
        ),
    ]
