# Generated by Django 5.0.6 on 2024-10-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_rename_id_person_army_id_warrior'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='army',
            name='image',
        ),
        migrations.AddField(
            model_name='army',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
