# Generated by Django 5.0.6 on 2024-10-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_army_current_units_alter_army_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='box_bronze',
            field=models.BooleanField(default=False, verbose_name='Забрал бронзовый сундук/нет'),
        ),
        migrations.AddField(
            model_name='person',
            name='box_gold',
            field=models.BooleanField(default=False, verbose_name='Забрал золотой сундук/нет'),
        ),
        migrations.AddField(
            model_name='person',
            name='box_silver',
            field=models.BooleanField(default=False, verbose_name='Забрал серебренный сундук/нет'),
        ),
    ]
